Repository datavorous/yars, pull requests merged in 2024-10, with the labels that each got.

#7 Implement ability to set user agent and randomize user agent
  yars/yars/agents.py
  yars/yars/yars.py
Labels: hacktoberfest-accepted

#9 Black formatting
  .pre-commit-config.yaml
  README.md
  pyproject.toml
  yars/README.md
  yars/yars/__init__.py
  yars/yars/example.py
  yars/yars/example2.py
  yars/yars/utils.py
  yars/yars/yars.py
Labels: hacktoberfest, hacktoberfest-accepted

#10 Updates For Issue #6
  .pre-commit-config.yaml
  README.md
  pyproject.toml
  yars/README.md
  yars/poetry.lock
  yars/pyproject.toml
  yars/tests/example1.py
  yars/tests/example2.py
  yars/tests/test_utils.py
  yars/tests/test_yars.py
  yars/yars/utils.py
  yars/yars/yars.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#17 Update yars.py
  src/yars/yars.py
Labels: enhancement, hacktoberfest, assigned, hacktoberfest-accepted

#18 Add functionality to search a specific subreddit using a keyword
  src/yars/yars.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#19 chore: separate example.py and uv.lock outside src
  README.md
  example/example.py
  uv.lock
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted
